# Generated by Django 3.1.5 on 2021-01-07 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210107_0916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='images',
            new_name='image',
        ),
    ]
